### ISSUE TITLE
Grouping of the basics

### ISSUE THREAD

**Issue by bittib010** [amestofortytwo/interactivekqlcheatsheet#1]
I want to group the basics like this (old code manually written):
![image](https://user-images.githubusercontent.com/77796831/216839802-fb830243-6abb-4207-9d9d-f00caa7dd454.png)

**Comment by bittib010** [comment]
How about using tags as a way of grouping queries like the screenshot above? And change the searching function to not work on tags, but on code, description and title (with checkboxes for each and one for all(default))?

If we change it to this - we should do tagging like: "basic", "intermediate", "advanced", "aggregated", "sentinel", "365" and maybe set all tags to only one. Or more? if more, we can duplicate the queries into all the relevant groupings, making the user looking for something to spend less time searhing. Maybe even change the wording from "tags" to "category" or similar...

@remiks thoughts?

**Comment by remiks** [comment]
Not sure I understood this... Can you try a design of it in some way?

**Comment by bittib010** [comment]
Too timeconsuming to jump into right now. Basically the category value(s) will make a parent <details> and <summary> of all queries (structured like they already are). If I am looking for "basic" queries, I dropdown that section and all the queries with the category "basic" are there. But some queries might overlap in these terms, and therefore be in multiple sections - a query might be both basic and belong to sentinel. Accepting that these gets duplicated, you have a higher chance of finding whatever you need quicker.

**Comment by remiks** [comment]
Aha! Now I understand. Alright. Yes. What about just adding a category property to the json so we can get both tags and category?

And instead of using check boxes for filter you can just write a search string ex "search basic sentinel"?

**Comment by bittib010** [comment]
Yeah, we might just add in the category. I didnt say so, but I kinda feel the tags part is redundant in that chaning where the search applies we will have duplicate values inside tags - almost only duplicates.

I like the searching thought. Solving things to make it become more intuitive is a great addition!

And also, another thougth - could we leverage the power of CTRL+F? by solving the issue on expand all, CTRL+F gets more power.
