### ISSUE TITLE
Expand all details function

### ISSUE THREAD

**Issue by bittib010** [amestofortytwo/interactivekqlcheatsheet#25]
By expanding them all, CTRL+F suddenly gets more power. Search on tags itself is powerfull, but also relies on the author to know what a query solves and forces the author to know what a good search tag is.

**Comment by bittib010** [comment]
And close all ofcourse

**Comment by remiks** [comment]
why do we need this? We have a powerful searcher at the top?

**Comment by bittib010** [comment]
> why do we need this? We have a powerful searcher at the top?

Agreed! Old issue, the search now is more powerfull than what this would allow and more intuitive! Closing it.

**Comment by bittib010** [comment]
Current search function is better than what ctrl+f wpuld allow with everything opened.
